### ISSUE TITLE
6.5.5 Get-CMDriverPackage -Fast paramater not found, line 19121

### ISSUE THREAD

**Issue by patrick-massie** [maurice-daly/DriverAutomationTool#243] opened 2021-06-24 01:57 UTC
Importing drivers to driver packages (ConfigMgr - Driver Pkg) against MECM 2010 returns the following error on 6.5.5 (Beta) in the PowerShell output window.

Get-CMDriverPackage : A parameter cannot be found that matches parameter name 'Fast'.
At line:19121 char:82
+ ... ID = (Get-CMDriverPackage -Name $CMDriverPackage.Trim() -Fast | Selec ...
+                                                             ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-CMDriverPackage], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.ConfigurationManagement.Cmdlets.Osd.Commands.GetDriverPackage

Also, -Fast parameter with Get-CMDriverPackage + "Cleanup unused drivers" will not Try/Catch the error and will delete all drivers from the SCCM database. The error is also not logged to the file.

**Comment by patrick-massie** [comment] 2021-06-24 13:01
The previous error only appears in  6.5.5 in the PowerShell output window.
The following is also logged to the DriverAutomationTool.log in 6.5.2, 6.5.3. 6.5.4 and 6.5.5. 

======== Errors(s) Occurred ========	DriverAutomationTool	6/22/2021 6:09:39 PM	10332 (0x285C)
Error: The SMS Provider reported an error. System.Management.ManagementException: Generic failure 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObject.Put(PutOptions options)
   at Microsoft.ConfigurationManagement.ManagementProvider.WqlQueryEngine.WqlResultObject.Put(ReportProgress progressReport)	DriverAutomationTool	6/22/2021 6:09:40 PM	10332 (0x285C)
 	DriverAutomationTool	6/22/2021 6:09:40 PM	10332 (0x285C)
ConfigMgr: Running driver import process (this might take several minutes)	DriverAutomationTool	6/22/2021 6:09:40 PM	10332 (0x285C)
======== Errors(s) Occurred ========	DriverAutomationTool	6/22/2021 6:09:40 PM	10332 (0x285C)
Error: Errors occurred while creating driver package	DriverAutomationTool	6/22/2021 6:09:40 PM	10332 (0x285C)
 	DriverAutomationTool	6/22/2021 6:09:40 PM	10332 (0x285C)

**Comment by patrick-massie** [comment] 2021-06-24 22:43
The -Fast parameter was added to a bunch of cmdlets in version 2103.

**Comment by sheicher** [comment] 2021-08-19 21:29
I can confirm the same thing is happening to me.  I'm using MECM 2006.  I'm trying to get Lenovo laptop drivers for Windows 10 20H2.  It's worth noting I don't really see it 

Get-CMDriverPackage : A parameter cannot be found that matches parameter name 'Fast'.
At line:19121 char:82
+ ... ID = (Get-CMDriverPackage -Name $CMDriverPackage.Trim() -Fast | Selec ...
+                                                             ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-CMDriverPackage], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.ConfigurationManagement.Cmdlets.Osd.Commands.GetDriverPackageCommand
 
Here's what's out of the logs...

======== Starting Download Processes ========	DriverAutomationTool	8/19/2021 4:22:27 PM	11936 (0x2EA0)
Info: Models selected: Lenovo ThinkPad E15 Gen 3	DriverAutomationTool	8/19/2021 4:22:27 PM	11936 (0x2EA0)
Info: Operating System specified: Windows 10	DriverAutomationTool	8/19/2021 4:22:27 PM	11936 (0x2EA0)
Info: Operating System architecture specified: x64	DriverAutomationTool	8/19/2021 4:22:27 PM	11936 (0x2EA0)
Info: Site Code specified: <Site Code>	DriverAutomationTool	8/19/2021 4:22:27 PM	11936 (0x2EA0)
Info: Download Path specified: \\<MECM Source Server>\Drivers\Source\Download	DriverAutomationTool	8/19/2021 4:22:27 PM	11936 (0x2EA0)
Info: Package Path specified: \\<MECM Source Server>\Drivers\Packages	DriverAutomationTool	8/19/2021 4:22:27 PM	11936 (0x2EA0)
Info: Windows 10 build lookup required	DriverAutomationTool	8/19/2021 4:22:27 PM	11936 (0x2EA0)
Info: Windows 10 build 10.0.19042.1 and version 20H2 identified for driver match	DriverAutomationTool	8/19/2021 4:22:27 PM	11936 (0x2EA0)
======== Processing Lenovo ThinkPad E15 Gen 3 Downloads ========	DriverAutomationTool	8/19/2021 4:22:27 PM	11936 (0x2EA0)
Info: Starting Download, extract and import processes for Lenovo model: ThinkPad E15 Gen 3	DriverAutomationTool	8/19/2021 4:22:27 PM	11936 (0x2EA0)
Info: Setting Lenovo variables	DriverAutomationTool	8/19/2021 4:22:27 PM	11936 (0x2EA0)
Info: Lenovo ThinkPad E15 Gen 3 matching model type: 20YJ 20YG 20YH 20YK	DriverAutomationTool	8/19/2021 4:22:27 PM	11936 (0x2EA0)
Info: Looking up Lenovo ThinkPad E15 Gen 3 URL For Windows version win10	DriverAutomationTool	8/19/2021 4:22:27 PM	11936 (0x2EA0)
Info: OS Version is 20H2	DriverAutomationTool	8/19/2021 4:22:27 PM	11936 (0x2EA0)
Info: Driver package URL - https://download.lenovo.com/pccbbs/mobiles/tp_e14gen3_mt20y7-mt20yd-mt20ye-mt20yf-e15gen3_mt20yg-mt20yh-mt20yj-mt20yk_w1064_20h2_20210414.exe	DriverAutomationTool	8/19/2021 4:22:28 PM	11936 (0x2EA0)
Info: Using Configuration Manager console BIOS package folder - <Site Code>:\Package\BIOS Packages\Lenovo	DriverAutomationTool	8/19/2021 4:22:38 PM	11936 (0x2EA0)
Info: Using Configuration Manager console Driver package folder - <Site Code>:\Package\Driver Packages\Lenovo	DriverAutomationTool	8/19/2021 4:22:38 PM	11936 (0x2EA0)
Info: Driver extract location set - \\<MECM Source Server>\Drivers\Source\Download\Lenovo\ThinkPad E15 Gen 3\Windows10-20H2-x64-20210414	DriverAutomationTool	8/19/2021 4:22:38 PM	11936 (0x2EA0)
Info: Driver package location set - \\<MECM Source Server>\Drivers\Packages\Lenovo\ThinkPad E15 Gen 3\Windows10-20H2-x64-20210414	DriverAutomationTool	8/19/2021 4:22:38 PM	11936 (0x2EA0)
======== Lenovo ConfigMgr ThinkPad E15 Gen 3 DRIVER PROCESSING STARTED ========	DriverAutomationTool	8/19/2021 4:22:38 PM	11936 (0x2EA0)
ConfigMgr: Latest driver revision found - 20210414	DriverAutomationTool	8/19/2021 4:22:38 PM	11936 (0x2EA0)
ConfigMgr: New driver package detected - Processing	DriverAutomationTool	8/19/2021 4:22:39 PM	11936 (0x2EA0)
ConfigMgr: Creating ThinkPad E15 Gen 3 download folder	DriverAutomationTool	8/19/2021 4:22:39 PM	11936 (0x2EA0)
ConfigMgr: Creating \\<MECM Source Server>\Drivers\Source\Download\Lenovo\ThinkPad E15 Gen 3\Driver Cab folder 	DriverAutomationTool	8/19/2021 4:22:39 PM	11936 (0x2EA0)
ConfigMgr: Downloading tp_e14gen3_mt20y7-mt20yd-mt20ye-mt20yf-e15gen3_mt20yg-mt20yh-mt20yj-mt20yk_w1064_20h2_20210414.exe	DriverAutomationTool	8/19/2021 4:22:39 PM	11936 (0x2EA0)
ConfigMgr: Downloading from URL: https://download.lenovo.com/pccbbs/mobiles/tp_e14gen3_mt20y7-mt20yd-mt20ye-mt20yf-e15gen3_mt20yg-mt20yh-mt20yj-mt20yk_w1064_20h2_20210414.exe	DriverAutomationTool	8/19/2021 4:22:39 PM	11936 (0x2EA0)
BitsTransfer: Checking BITS background job	DriverAutomationTool	8/19/2021 4:22:45 PM	11936 (0x2EA0)
BitsTransfer: Downloaded 102.25 MB of 320.08 MB (32%). Next update in 30 seconds.	DriverAutomationTool	8/19/2021 4:22:45 PM	11936 (0x2EA0)
ConfigMgr: Reported file byte size size: 335632880	DriverAutomationTool	8/19/2021 4:23:17 PM	11936 (0x2EA0)
ConfigMgr: Downloaded file byte size:  335632880	DriverAutomationTool	8/19/2021 4:23:17 PM	11936 (0x2EA0)
ConfigMgr: tp_e14gen3_mt20y7-mt20yd-mt20ye-mt20yf-e15gen3_mt20yg-mt20yh-mt20yj-mt20yk_w1064_20h2_20210414.exe - File exists processing driver package	DriverAutomationTool	8/19/2021 4:23:17 PM	11936 (0x2EA0)
ConfigMgr: tp_e14gen3_mt20y7-mt20yd-mt20ye-mt20yf-e15gen3_mt20yg-mt20yh-mt20yj-mt20yk_w1064_20h2_20210414.exe - File size verified	DriverAutomationTool	8/19/2021 4:23:17 PM	11936 (0x2EA0)
==================== ConfigMgr DRIVER EXTRACT ====================	DriverAutomationTool	8/19/2021 4:23:17 PM	11936 (0x2EA0)
ConfigMgr: Expanding driver CAB source file: tp_e14gen3_mt20y7-mt20yd-mt20ye-mt20yf-e15gen3_mt20yg-mt20yh-mt20yj-mt20yk_w1064_20h2_20210414.exe	DriverAutomationTool	8/19/2021 4:23:17 PM	11936 (0x2EA0)
ConfigMgr: Driver CAB destination directory: \\<MECM Source Server>\Drivers\Source\Download\Lenovo\ThinkPad E15 Gen 3\Windows10-20H2-x64-20210414	DriverAutomationTool	8/19/2021 4:23:17 PM	11936 (0x2EA0)
ConfigMgr: Using Lenovo silent switches: /VERYSILENT /DIR="\\<MECM Source Server>\Drivers\Source\Download\Lenovo\ThinkPad E15 Gen 3\Windows10-20H2-x64-20210414"	DriverAutomationTool	8/19/2021 4:23:17 PM	11936 (0x2EA0)
ConfigMgr: Extracting Lenovo drivers to \\<MECM Source Server>\Drivers\Source\Download\Lenovo\ThinkPad E15 Gen 3\Windows10-20H2-x64-20210414	DriverAutomationTool	8/19/2021 4:23:17 PM	11936 (0x2EA0)
ConfigMgr: Waiting for extract process (Process: tp_e14gen3_mt20y7-mt20yd-mt20ye-mt20yf-e15gen3_mt20yg-mt20yh-mt20yj-mt20yk_w1064_20h2_20210414) to complete..  Next check in 30 seconds	DriverAutomationTool	8/19/2021 4:23:34 PM	11936 (0x2EA0)
ConfigMgr: Waiting for extract process (Process: tp_e14gen3_mt20y7-mt20yd-mt20ye-mt20yf-e15gen3_mt20yg-mt20yh-mt20yj-mt20yk_w1064_20h2_20210414) to complete..  Next check in 30 seconds	DriverAutomationTool	8/19/2021 4:24:04 PM	11936 (0x2EA0)
ConfigMgr: Waiting for extract process (Process: tp_e14gen3_mt20y7-mt20yd-mt20ye-mt20yf-e15gen3_mt20yg-mt20yh-mt20yj-mt20yk_w1064_20h2_20210414) to complete..  Next check in 30 seconds	DriverAutomationTool	8/19/2021 4:24:34 PM	11936 (0x2EA0)
ConfigMgr: Waiting for extract process (Process: tp_e14gen3_mt20y7-mt20yd-mt20ye-mt20yf-e15gen3_mt20yg-mt20yh-mt20yj-mt20yk_w1064_20h2_20210414) to complete..  Next check in 30 seconds	DriverAutomationTool	8/19/2021 4:25:04 PM	11936 (0x2EA0)
ConfigMgr: Checking for extracted drivers	DriverAutomationTool	8/19/2021 4:25:34 PM	11936 (0x2EA0)
ConfigMgr: Import into is ConfigMgr - Driver Pkg	DriverAutomationTool	8/19/2021 4:25:34 PM	11936 (0x2EA0)
ConfigMgr: Driver count in path \\<MECM Source Server>\Drivers\Source\Download\Lenovo\ThinkPad E15 Gen 3\Windows10-20H2-x64-20210414 - 60 	DriverAutomationTool	8/19/2021 4:25:35 PM	11936 (0x2EA0)
==================== ConfigMgr DRIVER IMPORT ====================	DriverAutomationTool	8/19/2021 4:25:35 PM	11936 (0x2EA0)
ConfigMgr: Creating driver package Lenovo ThinkPad E15 Gen 3 - Windows 10 20H2 x64	DriverAutomationTool	8/19/2021 4:25:35 PM	11936 (0x2EA0)
ConfigMgr: Searching for driver INF files in \\<MECM Source Server>\Drivers\Source\Download\Lenovo\ThinkPad E15 Gen 3\Windows10-20H2-x64-20210414	DriverAutomationTool	8/19/2021 4:25:35 PM	11936 (0x2EA0)
ConfigMgr: Source directory \\<MECM Source Server>\Drivers\Source\Download\Lenovo\ThinkPad E15 Gen 3\Windows10-20H2-x64-20210414	DriverAutomationTool	8/19/2021 4:25:36 PM	11936 (0x2EA0)
ConfigMgr: Destination directory \\<MECM Source Server>\Drivers\Packages\Lenovo\ThinkPad E15 Gen 3\Windows10-20H2-x64-20210414\DriverPkg\	DriverAutomationTool	8/19/2021 4:25:36 PM	11936 (0x2EA0)
ConfigMgr: Creating Package for Lenovo ThinkPad E15 Gen 3 (Version 20210414)	DriverAutomationTool	8/19/2021 4:25:36 PM	11936 (0x2EA0)
ConfigMgr: Category already exists	DriverAutomationTool	8/19/2021 4:25:37 PM	11936 (0x2EA0)
ConfigMgr: Creating driver package for Lenovo ThinkPad E15 Gen 3 (Version 20210414)	DriverAutomationTool	8/19/2021 4:25:37 PM	11936 (0x2EA0)
ConfigMgr: Driver package name is Lenovo ThinkPad E15 Gen 3 - Windows 10 20H2 x64	DriverAutomationTool	8/19/2021 4:25:37 PM	11936 (0x2EA0)
ConfigMgr: Path to drivers is \\<MECM Source Server>\Drivers\Packages\Lenovo\ThinkPad E15 Gen 3\Windows10-20H2-x64-20210414\DriverPkg\	DriverAutomationTool	8/19/2021 4:25:37 PM	11936 (0x2EA0)
ConfigMgr: Creating driver package	DriverAutomationTool	8/19/2021 4:25:37 PM	11936 (0x2EA0)
ConfigMgr: New driver package name: Lenovo ThinkPad E15 Gen 3 - Windows 10 20H2 x64 | Path \\<MECM Source Server>\Drivers\Packages\Lenovo\ThinkPad E15 Gen 3\Windows10-20H2-x64-20210414\DriverPkg\	DriverAutomationTool	8/19/2021 4:25:38 PM	11936 (0x2EA0)
======== Errors(s) Occurred ========	DriverAutomationTool	8/19/2021 4:25:39 PM	11936 (0x2EA0)
Error: A parameter cannot be found that matches parameter name 'Fast'. 	DriverAutomationTool	8/19/2021 4:25:39 PM	11936 (0x2EA0)
 	DriverAutomationTool	8/19/2021 4:25:39 PM	11936 (0x2EA0)
ConfigMgr: Running driver import process (this might take several minutes)	DriverAutomationTool	8/19/2021 4:25:39 PM	11936 (0x2EA0)
======== Errors(s) Occurred ========	DriverAutomationTool	8/19/2021 4:25:39 PM	11936 (0x2EA0)
Error: Errors occurred while creating driver package	DriverAutomationTool	8/19/2021 4:25:39 PM	11936 (0x2EA0)
 	DriverAutomationTool	8/19/2021 4:25:39 PM	11936 (0x2EA0)
======== Lenovo ConfigMgr ThinkPad E15 Gen 3 DRIVER PROCESSING FINISHED ========	DriverAutomationTool	8/19/2021 4:25:39 PM	11936 (0x2EA0)
Info: Remaining models to process: 0	DriverAutomationTool	8/19/2021 4:25:39 PM	11936 (0x2EA0)
======== Clean Up Driver Option Processing ========	DriverAutomationTool	8/19/2021 4:25:39 PM	11936 (0x2EA0)
ConfigMgr: Removing driver download and extracted source driver files from \\<MECM Source Server>\Drivers\Source\Download	DriverAutomationTool	8/19/2021 4:25:39 PM	11936 (0x2EA0)
ConfigMgr: Removing source content from \\<MECM Source Server>\Drivers\Source\Download\Lenovo\ThinkPad E15 Gen 3\Driver Cab	DriverAutomationTool	8/19/2021 4:25:40 PM	11936 (0x2EA0)
ConfigMgr: Removing source content from \\<MECM Source Server>\Drivers\Source\Download\Lenovo\ThinkPad E15 Gen 3\Windows10-20H2-x64-20210414	DriverAutomationTool	8/19/2021 4:25:40 PM	11936 (0x2EA0)
ConfigMgr: Removing empty source content from \\<MECM Source Server>\Drivers\Source\Download\Lenovo\ThinkPad E15 Gen 3	DriverAutomationTool	8/19/2021 4:25:44 PM	11936 (0x2EA0)
======== FINISHED PROCESSING ========	DriverAutomationTool	8/19/2021 4:25:44 PM	11936 (0x2EA0)

**Comment by sheicher** [comment] 2021-09-08 16:45
I updated my DriverAutomationTool to 6.5.6.  I'm disappointed this problem still exists.

**Comment by rtruss** [comment] 2021-09-21 12:19
> The -Fast parameter was added to a bunch of cmdlets in version 2103.

So you are saying "it's fixed in the next version". ;)  

I too am seeing this with dat 6.5.6 and you are saying to update ConfigMgr to 2103 or 2107 and the -FAST switch error I am getting will go away?  If so I can live with that for another month until my 2107 update change happens.

This is probably the most important tool I have for OSD in Configmgr and it rocks!

**Comment by sheicher** [comment] 2021-09-21 12:46
> > The -Fast parameter was added to a bunch of cmdlets in version 2103.
> 
> So you are saying "it's fixed in the next version". ;)
> 
> I too am seeing this with dat 6.5.6 and you are saying to update ConfigMgr to 2103 or 2107 and the -FAST switch error I am getting will go away? If so I can live with that for another month until my 2107 update change happens.
> 
> This is probably the most important tool I have for OSD in Configmgr and it rocks!

It was originally reported in 6.5.5, but still here in 6.5.6.  I had hopes it was fixed, but nope.  I have my MECM update on my list, but I can't exactly do it with my backlog of tasks and project.  That was after getting me up from 1803 to 2006 earlier this year.

**Comment by jipijajay** [comment] 2021-11-23 12:15
Same issue here.. (2007) update is planned but until then do I have any chance to fix it?
I was looking for the .ps1 to just remove the parameter but it looks like that the ps1 is also gone since DAT version 5. So I am using 6.4. until we can update to 2111.

**Comment by rtruss** [comment] 2021-11-23 12:52
I am planning on upgrading tomorrow to 2107 and can advise as to error status after as I have been seeing that as well.

**Comment by harveybham** [comment] 2022-01-07 09:38
Hi @rtruss did you do the upgrade?

I am also on version 2006 and have the same issue. Before upgrading i wanted to see if you have fixed the issue by upgrading to 2107

**Comment by rtruss** [comment] 2022-01-07 13:21
> Hi @rtruss did you do the upgrade?
> 
> I am also on version 2006 and have the same issue. Before upgrading i wanted to see if you have fixed the issue by upgrading to 2107

Can confirm, no more messages post 2107 upgrade using DAT 7.0.1.  Sorry about not reporting earlier all.  Got tied up with end of year stuff.  Happy new year all.

**Comment by harveybham** [comment] 2022-01-07 13:46
> > Hi @rtruss did you do the upgrade?
> > I am also on version 2006 and have the same issue. Before upgrading i wanted to see if you have fixed the issue by upgrading to 2107
> 
> Can confirm, no more messages post 2107 upgrade using DAT 7.0.1. Sorry about not reporting earlier all. Got tied up with end of year stuff. Happy new year all.

No problem at all. Thanks for confirming. I'll fit the upgrade in. Happy new year to you also

**Comment by maurice-daly** [comment] 2022-03-09 15:32
Fixed in latest release

**Closed** 2022-03-09 15:32 UTC
