### ISSUE TITLE
Lenovo Driver not downloading

### ISSUE THREAD

**Issue by techygeekshome** [maurice-daly/DriverAutomationTool#401] opened 2022-10-12 12:33 UTC
I'm trying to add the Lenovo ThinkStation P330 Tiny drive, but getting an error...

![image](https://user-images.githubusercontent.com/41306705/195343620-741029fe-0d05-4012-b8ac-6e4e35db481e.png)

**Comment by NeighborGeek** [comment] 2022-10-19 19:19
I'm seeing similar behavior with other lenovo models.  In my case, I was downloading both BIOS and Driver packages, so after the same error as in your screenshot ("Unable to find driver for Lenovo Thinkcentre M920Q" for mine) it moved on to trying to find and download a BIOS update as well.  
There's a bit more information in the log for the BIOS download, as you can see in the log section below.  
`
======== Processing Lenovo ThinkCentre M920Q Downloads ========	DriverAutomationTool	10/19/2022 1:48:58 PM	24840 (0x6108)
- Starting Download, extract and import processes for Lenovo model: ThinkCentre M920Q	DriverAutomationTool	10/19/2022 1:48:58 PM	24840 (0x6108)
- Setting Lenovo variables	DriverAutomationTool	10/19/2022 1:48:58 PM	24840 (0x6108)
- Lenovo ThinkCentre M920Q matching model type: 10RS 10T1 10UH 10V8 10RR 10SY 10T2 10RT 10RU	DriverAutomationTool	10/19/2022 1:48:58 PM	24840 (0x6108)
- Looking up version based on 21H2 and OS based on Windows 10	DriverAutomationTool	10/19/2022 1:48:58 PM	24840 (0x6108)
- BETA: Driver Download is  and type is All	DriverAutomationTool	10/19/2022 1:48:58 PM	24840 (0x6108)
======== Errors(s) Occurred ========	DriverAutomationTool	10/19/2022 1:48:58 PM	24840 (0x6108)
[Error] - Unable to find driver for Lenovo ThinkCentre M920Q	DriverAutomationTool	10/19/2022 1:48:58 PM	24840 (0x6108)
 	DriverAutomationTool	10/19/2022 1:48:58 PM	24840 (0x6108)
- Using Configuration Manager console BIOS package folder - CHC:\Package\BIOS Packages\Lenovo	DriverAutomationTool	10/19/2022 1:49:04 PM	24840 (0x6108)
- Using Configuration Manager console Driver package folder - CHC:\Package\Driver Packages\Lenovo	DriverAutomationTool	10/19/2022 1:49:04 PM	24840 (0x6108)
======== Lenovo ThinkCentre M920Q BIOS PROCESSING STARTED ========	DriverAutomationTool	10/19/2022 1:49:04 PM	24840 (0x6108)
- Retrieving BIOS download URL for Lenovo Client Model: ThinkCentre M920Q	DriverAutomationTool	10/19/2022 1:49:04 PM	24840 (0x6108)
- Attempting to find download URL using Find-LenovoBIOS function	DriverAutomationTool	10/19/2022 1:49:04 PM	24840 (0x6108)
Lenovo Base - https://download.lenovo.com/catalog/, Lenovo Model Type 10RS	DriverAutomationTool	10/19/2022 1:49:04 PM	24840 (0x6108)
- Quering XML https://download.lenovo.com/catalog/10RS_Win10.xml for BIOS download links 	DriverAutomationTool	10/19/2022 1:49:04 PM	24840 (0x6108)
- Downloading BIOS update from https://download.lenovo.com/pccbbs/thinkcentre_bios/m1ujy6busa_2_.xml 	DriverAutomationTool	10/19/2022 1:49:04 PM	24840 (0x6108)
**- Found exe file link: n23uj35w.exe**	DriverAutomationTool	10/19/2022 1:49:04 PM	24840 (0x6108)
- BIOS version is M1UKT6BA	DriverAutomationTool	10/19/2022 1:49:04 PM	24840 (0x6108)
- Checking ConfigMgr for existing BIOS release - M1UKT6BA	DriverAutomationTool	10/19/2022 1:49:04 PM	24840 (0x6108)
- Comparing BIOS versions	DriverAutomationTool	10/19/2022 1:49:04 PM	24840 (0x6108)
- New BIOS download available	DriverAutomationTool	10/19/2022 1:49:04 PM	24840 (0x6108)
- BIOS update directory set to \\chc-cm.davchc.com\drivers$\DRIVERPACKAGES\DRIVERAUTOMATIONPKGS\Lenovo\ThinkCentre M920Q\BIOS\M1UKT6BA\	DriverAutomationTool	10/19/2022 1:49:04 PM	24840 (0x6108)
- Downloading BIOS update file from https://download.lenovo.com/pccbbs/thinkcentre_bios/n23uj35w.exe	DriverAutomationTool	10/19/2022 1:49:04 PM	24840 (0x6108)
- BitsTransfer: Checking BITS background job	DriverAutomationTool	10/19/2022 1:49:05 PM	24840 (0x6108)
- BitTransfer: Job state is ""	DriverAutomationTool	10/19/2022 1:49:05 PM	24840 (0x6108)
======== Errors(s) Occurred ========	DriverAutomationTool	10/19/2022 1:49:05 PM	24840 (0x6108)
[Error] - BIOS failed to download. Check log for more details	DriverAutomationTool	10/19/2022 1:49:05 PM	24840 (0x6108)
 	DriverAutomationTool	10/19/2022 1:49:05 PM	24840 (0x6108)
======== Lenovo ThinkCentre M920Q BIOS PROCESSING FINISHED ========	DriverAutomationTool	10/19/2022 1:49:05 PM	24840 (0x6108)
`
One thing stands out to me, "- Found exe file link:n23uj35w.exe"  That exe file name doesn't match the m1ujy6busa_2_.xml file it just downloaded for the bios version, and looking at the content of m1ujy6busa_2_.xml I don't see n23uj35w.exe anywhere in there, so it's not getting that exe name from this XML file. 
I've found that n23uj35w.exe is actually the bios update file for the previously processed model, a "Lenovo ThinkPad X1 Carbon 6th Gen".  It seems like for the script is downloading the right xml files for each model's drivers, but failing to parse them correctly to get the correct driver and bios update files for each model.  
I'm also seeing the below errors in the DAT script window, which seem consistent with DAT not parsing the xml correctly to get the download link: 
`You cannot call a method on a null-valued expression.
At line:19779 char:10
+ ...             $BIOSFile = ($LenovoBIOSDetails.ExtractCommand).Split(" " ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Start-BitsTransfer : HTTP status 404: The requested URL does not exist on the server.
At line:19832 char:14
+ ...             Start-BitsTransfer $BIOSFileDownload -Destination "$($BIO ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-BitsTransfer], Exception
    + FullyQualifiedErrorId : StartBitsTransferCOMException,Microsoft.BackgroundIntelligentTransfer.Management.NewBitsTransferCommand
`

Hopefully that is points to where things are going wrong.  

Thanks!
Steve

**Comment by maurice-daly** [comment] 2022-11-26 14:50
P330 Tiny not found in Windows 10 only XML, unable to reproduce. Closing issue.

**Closed by maurice-daly** 2022-11-26 14:50 UTC
