### ISSUE TITLE
Freezes adding Microsoft Models

### ISSUE THREAD

**Issue by bobojobaxter** [maurice-daly/DriverAutomationTool#420] opened 2022-11-10 18:32 UTC
```
You cannot call a method on a null-valued expression.
At line:17143 char:5
+ ...             $OSBuild = ($WindowsBuildHashTable.Item("$OSBuild")).Spli ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

```

once it gets to that spot, I can't do anything and I can't uncheck microsoft either. I can't access any drop down :/

**Comment by pet30201** [comment] 2022-11-10 21:30
Also having this same issue.

**Comment by maurice-daly** [comment] 2022-11-26 14:52
Unable to reproduce. Closing issue.

**Closed by maurice-daly** 2022-11-26 14:52 UTC
