### ISSUE TITLE
Creating empty driver packages

### ISSUE THREAD

**Issue by ChrisCalaf** [maurice-daly/DriverAutomationTool#265] opened 2021-09-11 20:32 UTC
Using 6.5.6 with HP machines. According to the logs, I can see the drivers download, extract, and create the packages. The logs reference the source of the files, but the directory is empty. The only errors we see is the "Error: A parameter cannot be found that matches parameter name 'Fast'. " which has been mentioned before. I have verified permissions and even created a new source share so the paths are shorter.

**Comment by sheicher** [comment] 2021-09-15 18:36
Duplicate of #243 - same symptoms.

**Closed** 2022-03-09 15:32 UTC
